### ISSUE TITLE
Add an --init-on-fail option

### ISSUE THREAD

**Issue by scottleibrand** [bewest/decoding-carelink#46]
On commands that require a recent --init to work, we should have an option (maybe called --init-on-fail or similar) that tries the command without --init first (since that's much faster if it works) and then does an --init if that fails on the first try.  We should also make it possible to to get the behavior without a command-line argument, maybe by reading some sort of environment variable (maybe INIT_ON_FAIL=true).

Thoughts?

**Comment by bewest** [comment]
This is now available via `--auto-init` switch, which will try to fetch the model number, and will try issuing PowerControlOn if it fails.  It will retry that entire sequence 3 times.  I've begun tuning the loops to fail faster, in order to make this a little quicker; this make some tools start much much slower.

Closing for now, but feel free to follow up/re-open.
