### ISSUE TITLE
mm-temp-basal says CRITICAL but sets temp basal

### ISSUE THREAD

**Issue by ktomy** [bewest/decoding-carelink#57]
<code>

pi@raspberrypi ~/decoding-carelink/bin $ python mm-temp-basals.py  --port /dev/ttyUSB0 --serial 639191 set --duration 120  --rate 0.1
## do stuff with an insulin pump over RF
using ` Namespace(command='set', dryrun=False, duration=120, init=False, no_postlude=False, no_prelude=False, no_rf_prelude=False, port='/dev/ttyUSB0', rate=0.1, serial='639191', verbose=None) `
```
```
```
```
```
```
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 315L,
           'packets.transmit': 324L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 1,
         'packets.received': 777L,
         'packets.transmit': 777L}}
```
```
```
### PUMP MODEL: `ReadPumpModel:size[64]:data:'715'`
WARNING:decocare.stick:bad zero CRC?
response: ReadBasalTemp:size[64]:data:{'duration': 0, 'rate': 0.0}
#### decoded:
```python
{'duration': 0, 'rate': 0.0}
```
CRITICAL:decocare.session:this seems like a problem
response: TempBasal:size[64]:data:bytearray(b'\x00')
hexdump:
```python
0000   0x00                                       .
```
#### decoded:
```python
bytearray(b'\x00')
```
response: ReadBasalTemp:size[64]:data:{'duration': 120, 'rate': 0.1}
#### decoded:
```python
{'duration': 120, 'rate': 0.1}
```
### end stats
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 320L,
           'packets.transmit': 329L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 1,
         'packets.received': 791L,
         'packets.transmit': 791L}}
```
pi@raspberrypi ~/decoding-carelink/bin $ python mm-temp-basals.py --init --port /dev/ttyUSB0 --serial 639191 query
## do stuff with an insulin pump over RF
using ` Namespace(command='query', dryrun=False, duration=0, init=True, no_postlude=False, no_prelude=False, no_rf_prelude=False, port='/dev/ttyUSB0', rate=0, serial='639191', verbose=None) `
```
```
```
```
```
```
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 320L,
           'packets.transmit': 329L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 1,
         'packets.received': 796L,
         'packets.transmit': 796L}}
```
```
PowerControl SERIAL 639191
```
### PUMP MODEL: `ReadPumpModel:size[64]:data:'715'`
response: ReadBasalTemp:size[64]:data:{'duration': 120, 'rate': 0.1}
#### decoded:
```python
{'duration': 120, 'rate': 0.1}
```
### end stats
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 324L,
           'packets.transmit': 333L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 1,
         'packets.received': 807L,
         'packets.transmit': 807L}}

</code>

**Comment by bewest** [comment]
That warning is produced anytime the CRC does not match or is null while transferring data from the pump to your local PC.  It turns out based on my analysis, that sometimes this is expected if not enough data has yet queued onto your local stick, but a dire warning is produced anyway.

https://github.com/bewest/decoding-carelink/issues/71 has some requests for better documenting the protocol and other things.  With better analysis of the protocol expectations, we can eliminate the dire warnings that are simply not needed.

It's worth noting that at the time of writing, these scripts were intended as a tool to develop and understand the protocol itself, which was unknown.   As a result, it is very conservative in terms of trying to perform exactly as the stick itself expects.  In some instances, I've seen some of the recovery logic actually work to "save/recover" ongoing transmissions, hopefully lots of reviewers can help suss out and document exactly what is going on.

**Comment by bewest** [comment]
The tl;dr version is the dire warnings are expected and can be ignored, so long as you are getting "clean counters" at the beginning and end.  If at any time the counters seem to have reversed, or produce nonsense numbers, the stick must be removed and plugged in again.

Closing for now, please jump in the other threads, or re-open this one if needed. :smile_cat:
